### ISSUE TITLE
mixing our own .cel with GSE references

### ISSUE THREAD

**Issue by abasseville** [alexvpickering/crossmeta#3]
Hi, 
Thank you for your package, it is very usefull, and seams easy to use with GEO references.
I have a question (more than an issue).
I would like to mix some GSE references with my own .CEL and sample annotation.
I found your very nice website https://rnama.com/app/datasets, but I am only interested in downloading, normalizing, and "gene annotating" the mixed data (geo and mine). My purpose is to obtain at the end a single matrix of all samples after normalization (I am not interested by DE genes)
Is there a way to do that?
Thank you for your help

agnes

**Comment by alexvpickering** [comment]
Hi Agnes,
That would take some customisation to accomplish. I would approach this as follows:

1. Use `load_raw` to load and annotate the raw GSE data. Dig into the source code of `crossmeta::load_raw` and adapt in order to do the same for your personal CEL files.

2. Then change the row names to something that is common between all studies (e.g. the `SYMBOL` column in `fData` of each eset). 

3. Then merge all the matrices on those common identifiers.

**Comment by abasseville** [comment]
Hi Alex,
Thank you for your response.
I looked into the source code , but I am not sure I understood everything (I am rather beginner in bioinformatics): I couldn't find the line in load_raw function and in the linked-functions (load_affy, ...) where the  "cross-platform effect size" is performed after the esets were properly loaded.
It seems for me that this step (which is es_meta if I understood well?) is done after the differential expression calculation . 
Did I miss something?

**Comment by abasseville** [comment]
Sorry,I understood my mistake, I wanted to do cross-platform normalization and not meta-analysis.
